---
- hosts: localhost
  tasks:
  - name: Ensure learning VM hostnames in /etc/hosts 
    diff: yes
    become: yes
    blockinfile:
      path: /etc/hosts
      marker: '# {mark} ANSIBLE MANAGED BLOCK - mdls'
      create: no
      state: present
      block: |
        # installing examples
          # avail 104,106,107
        192.168.30.101  getdc
        192.168.30.102  cli-only
        192.168.30.103  snappy
        192.168.30.105  archy
        192.168.30.108  centos-8
        192.168.30.109  binaries
        
        # security focused examples
        192.168.30.110  secured
        # 192.168.30.111  client-secured
        # 192.168.30.119  rootless
        
        # swarm examples (up to 4 swarm machines)
        192.168.30.130  swarm0
        192.168.30.131  swarm1
        192.168.30.132  swarm2
        192.168.30.133  swarm3 

        # todo k8s examples
        # I believe I will use minikube for k8s demos, not sure yet so I'm reserving address space just in case
        # 192.168.30.150 k8s1
